"""empty message

Revision ID: 410f4d54d1c0
Revises: a01477b51772
Create Date: 2019-09-19 16:00:54.133820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '410f4d54d1c0'
down_revision = 'a01477b51772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=16), nullable=True))
    op.drop_index('usernaem', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'usernaem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usernaem', mysql.VARCHAR(length=16), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('usernaem', 'user', ['usernaem'], unique=True)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
